# Dependencies
highlighter: rouge

# Permalinks
permalink: /:categories/:year/:month/:title/

# Setup
title: "A. Matías Quezada"
tagline: "Artista de Javascript"
description: "Artista de Javascript"
url: https://blog.amatiasq.com
baseurl: /

author:
  name: "A. Matías Quezada"
  url: https://amatiasq.com

paginate: 20

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/amatiasq/blog

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: amatiasq@gmail.com
  facebook:
  flickr:
  github: amatiasq/blog
  instagram:
  linkedin: https://www.linkedin.com/in/amatiasq/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: amatiasq
  stackoverflow: users/1721248/a-mat%C3%ADas-quezada
  youtube: user/amatiasq
  googleplus: # g+ user code

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: blog-amatiasq-com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-47319201-1

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
